### ISSUE TITLE
Hangs sending codes when override speed is not enabled

### ISSUE THREAD

**Issue by jasin** [OttoHermansson/GcodeSender#1]
Gcodesender seems to hang when I do not have the override speed box checked. I have a 205 line g-code file and every time it hangs up on line 10. The only way to get it past this part is to stop the streaming of the g-code file. Check the radio button for override speed and then start all over again. 

It would help if I was sure of what the override speed check box did. The way I see it, the lower the number the slower the processing, the bigger the number the faster the processing. I am using 0.6b grbl with an arduino uno. If you need my smiley.nc file to see if you can recreate the bug, I can send it through email. Really like this app and hope to use it in the future.

**Comment by OttoHermansson** [comment]
The speed override looks for F commands before sending the line to Grbl. If
it finds a F it replaces the number after with the number selected. Could
you send the file I'll have a look at it.

On Tue, Dec 20, 2011 at 9:34 AM, jasin <
reply@reply.github.com

**Comment by jasin** [comment]
I think I have narrowed down the issue and it does not seem to be gcodesender related. I am familiar with c# and after looking at your code I determined what the override function did. I then watched closely as to what was happening, it seems that grbl does not like F commands over 150. I can re-create this issue so far 100% of the time. The line in question has an F command of 300, if I set the override to 140 it works as desired, set to 150 and the arduino grinds to a halt. I will be reporting this to grbl, maybe it is an issue that they are aware of and I am just not understanding.

Though, on this note, I was wondering if we could ask gcodesender to modify the gcode slightly by having a MAX F value. So instead of overriding F commands of < 150, just override F commands > 150. 

Really do appreciate your app, so far it has worked the best out of all the ones I have tried as an interface to grbl.

**Comment by OttoHermansson** [comment]
That sounds like a bad combination of settings. I run my Grbl at about
F14000 without problem.

On Tue, Dec 20, 2011 at 3:45 PM, jasin <
reply@reply.github.com

**Comment by jasin** [comment]
Well that really bums me out, guess I will have to take a closer look at my grbl settings. I never did change any of the settings as I am just testing grbl out with your interface. I have my stepper driver disabled, so it is somewhere between the arduino itself and the grbl code programmed into it. 

May I ask what version of grbl you are using? I am using 0.6b with an arduino uno 328p

**Comment by OttoHermansson** [comment]
I'm using a two different versions as I use it in two laser cutters and one
mill. The laser cutters runs LasaurGrbl latest version and the mill run
0.6b.

All of them on UNO 328p.

On Tue, Dec 20, 2011 at 3:58 PM, jasin <
reply@reply.github.com

**Comment by jasin** [comment]
Well, I fixed my issue. I downloaded chamnit's 0.7d version of grbl and now it works so much better. I Used your app to run 5k lines gcode and it went flawlessly. I am not sure why 0.6b acted funny, but it really doesn't matter now.
